# Configuraci√≥n de Cargo para ADead
# Evitar bugs de VS 2025 Insiders con PDB (error LNK1318)

[target.x86_64-pc-windows-msvc]
# Deshabilitar completamente debug info y PDB
rustflags = ["-C", "debuginfo=0", "-C", "link-arg=/DEBUG:NONE"]
